#!/usr/bin/env node
/**
 * =====================================================================
 * PHANTOMTRACE - NODE.JS SCANNER HTTPS UPLOAD INTEGRATION
 * =====================================================================
 * Smallest safe integration layer for production (Node.js runtime).
 * Uploads scan_results.json generated by PhantomTrace Windows Scanner
 * (PhantomTrace_Windows_Release_1.0.exe) to the authenticated Node.js API.
 *
 * IMPORTANT:
 * - Scanner remains 100% READ-ONLY.
 * - Zero modification to process memory, behavior rules, or threat scoring.
 * =====================================================================
 */

import fs from "fs";
import path from "path";

const API_URL = process.env.PHANTOMTRACE_API_URL || process.argv[2] || "https://phantomtrace-web.onrender.com";
const AUTH_TOKEN = process.env.PHANTOMTRACE_AUTH_TOKEN || process.argv[3] || "";
const FILE_PATH = process.env.PHANTOMTRACE_SCAN_FILE || process.argv[4] || "sample_scanner_output/scan_results.json";

async function run() {
  const resolvedPath = path.resolve(FILE_PATH);
  if (!fs.existsSync(resolvedPath)) {
    console.error(`[ERROR] Scan file not found at: ${resolvedPath}`);
    process.exit(1);
  }

  const fileStats = fs.statSync(resolvedPath);
  const sizeMb = (fileStats.size / (1024 * 1024)).toFixed(2);

  console.log("============================================================");
  console.log(" PHANTOMTRACE SCAN INGESTION DISPATCHER (Node.js)");
  console.log(` Target API:  ${API_URL}`);
  console.log(` Source File: ${resolvedPath} (${sizeMb} MB)`);
  console.log("============================================================");

  const raw = fs.readFileSync(resolvedPath, "utf-8");
  const parsed = JSON.parse(raw);
  const processes = parsed.processes || parsed.results;
  if (!Array.isArray(processes)) {
    console.error("[ERROR] Invalid scan payload: missing 'processes' or 'results' collection.");
    process.exit(1);
  }

  console.log(`[+] Validated scan format. Processes to transmit: ${processes.length}`);

  const endpoint = `${API_URL.replace(/\/+$/, "")}/api/scans/ingest`;
  const res = await fetch(endpoint, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${AUTH_TOKEN}`,
      "User-Agent": "PhantomTrace-Windows-Agent/1.0",
    },
    body: raw,
  });

  const body = await res.json();
  if (!res.ok) {
    console.error(`[FAIL] Ingestion failed (Status ${res.status}):`, body);
    process.exit(1);
  }

  console.log(`[PASS] Ingestion complete. HTTP Status: ${res.status}`);
  console.log(`       Scan ID:            ${body.scanId}`);
  console.log(`       Endpoint ID:        ${body.endpointId}`);
  console.log(`       Processes Imported: ${body.processesImported}`);
  console.log(`       Alerts Imported:    ${body.alertsImported}`);
  console.log(`       Highest Score:      ${body.highestScore}/100`);
  if (body.duplicate) {
    console.log("       [NOTICE] Duplicate scan detected; existing record reused.");
  }
}

run().catch((err) => {
  console.error("[FAIL] Unexpected error:", err);
  process.exit(1);
});
