#!/usr/bin/env python3
"""
=====================================================================
PHANTOMTRACE - WINDOWS SCANNER HTTPS UPLOAD INTEGRATION
=====================================================================
Smallest safe integration layer for production.
Uploads scan_results.json generated by PhantomTrace Windows Scanner
(PhantomTrace_Windows_Release_1.0.exe) to the authenticated Node.js API.

IMPORTANT:
- Scanner remains 100% READ-ONLY.
- Does NOT modify memory, behavior detection, threat scoring, or files.
- Communicates strictly via HTTPS/REST API with Bearer token auth.
- Compatible with Python 3.8+ using standard library only (no pip required).
=====================================================================
"""

import sys
import os
import json
import argparse
import urllib.request
import urllib.error

DEFAULT_API_URL = os.environ.get("PHANTOMTRACE_API_URL", "https://phantomtrace-web.onrender.com")
DEFAULT_AUTH_TOKEN = os.environ.get("PHANTOMTRACE_AUTH_TOKEN", "")
DEFAULT_FILE_PATH = os.environ.get("PHANTOMTRACE_SCAN_FILE", "scan_results.json")

def upload_scan(api_url: str, auth_token: str, file_path: str) -> bool:
    if not os.path.exists(file_path):
        print(f"[ERROR] Scan file not found at: {file_path}")
        return False

    file_size_mb = os.path.getsize(file_path) / (1024 * 1024)
    print("=" * 60)
    print(" PHANTOMTRACE SCAN INGESTION DISPATCHER")
    print(f" Target API:  {api_url}")
    print(f" Source File: {file_path} ({file_size_mb:.2f} MB)")
    print("=" * 60)

    try:
        with open(file_path, "rb") as f:
            payload = f.read()

        # Validate that it is valid JSON with results array
        parsed = json.loads(payload.decode("utf-8"))
        if not isinstance(parsed, dict):
            print("[ERROR] Invalid scan payload: root must be a JSON object.")
            return False

        processes_list = parsed.get("processes") or parsed.get("results")
        if not isinstance(processes_list, list):
            print("[ERROR] Invalid scan payload: missing 'processes' or 'results' collection.")
            return False

        process_count = len(processes_list)
        print(f"[+] Validated PhantomTrace scanner format. Processes to transmit: {process_count}")

        endpoint = f"{api_url.rstrip('/')}/api/scans/ingest"
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {auth_token}",
            "User-Agent": "PhantomTrace-Windows-Agent/1.0",
        }

        req = urllib.request.Request(
            url=endpoint,
            data=payload,
            headers=headers,
            method="POST"
        )

        with urllib.request.urlopen(req) as response:
            status_code = response.getcode()
            response_body = response.read().decode("utf-8")
            data = json.loads(response_body)

            print(f"[PASS] Ingestion complete. HTTP Status: {status_code}")
            print(f"       Scan ID:            {data.get('scanId')}")
            print(f"       Endpoint ID:        {data.get('endpointId')}")
            print(f"       Processes Imported: {data.get('processesImported')}")
            print(f"       Alerts Imported:    {data.get('alertsImported')}")
            print(f"       Highest Score:      {data.get('highestScore')}/100")
            if data.get("duplicate"):
                print("       [NOTICE] Duplicate scan detected; existing record reused.")
            return True

    except urllib.error.HTTPError as e:
        print(f"[FAIL] HTTP Error {e.code}: {e.reason}")
        try:
            err_data = json.loads(e.read().decode("utf-8"))
            print(f"       Error details: {err_data}")
        except Exception:
            pass
        return False
    except urllib.error.URLError as e:
        print(f"[FAIL] Network Connection Error: {e.reason}")
        return False
    except Exception as e:
        print(f"[FAIL] Unexpected error: {str(e)}")
        return False

def main():
    parser = argparse.ArgumentParser(description="PhantomTrace Scanner HTTPS Ingestion Uploader")
    parser.add_argument("--api-url", default=DEFAULT_API_URL, help="Target API URL (e.g., https://api.phantomtrace.security)")
    parser.add_argument("--token", default=DEFAULT_AUTH_TOKEN, help="Firebase ID or Agent Bearer Auth Token")
    parser.add_argument("--file", default=DEFAULT_FILE_PATH, help="Path to scan_results.json")

    args = parser.parse_args()
    success = upload_scan(args.api_url, args.token, args.file)
    sys.exit(0 if success else 1)

if __name__ == "__main__":
    main()
